# Metadata
title: The Journal of Southern Religion
editors: Editors of the Journal of Southern Religion
webmaster_email: lincoln+jsr@lincolnmullen.com
currentissue: vol13

# Services and Feeds
disqus_shortname: journalofsouthernreligion
disqus_developer: 0      # 1 for dev site; 0 for live site
google_analytics_id: UA-31135305-1
github-repo: https://github.com/lmullen/jsr
podcast-feed: http://jsr.fsu.edu/itunes.xml         #link to Feedburner podcast feed
podcast-itunes: http://jsr.fsu.edu/itunes.xml       #link to iTunes store
all-posts-feed: http://jsr.fsu.edu/all.atom.xml     #link to Feedburner all posts feed
twitter-link: https://twitter.com/#!/jsreligion
facebook-link: http://www.facebook.com/pages/Journal-of-Southern-Religion/197375710340300

# Generation
source: .
destination: ./_site
plugins: ./_plugins
exclude: _working/, Rakefile, _bootstrap/, _backups/
auto: false
server: false
server_port: 4000
permalink: /:categories/:title.html
# baseurl and url are passed as command line options
