# Metadata
title: The Journal of Southern Religion
editors: Editors of the Journal of Southern Religion
webmaster_email: lincoln+jsr@lincolnmullen.com
issn: "1094-5253"
currentissue: vol15

# Services and Feeds
disqus_shortname: journalofsouthernreligion
disqus_developer: 0      # 1 for dev site; 0 for live site
google_analytics_id: UA-31135305-1
github-repo: https://github.com/lmullen/jsr
podcast-feed: http://feeds.feedburner.com/JSR-podcast       #link to Feedburner podcast feed
podcast-itunes: http://itunes.apple.com/us/podcast/journal-southern-religion/id523508035  #link to iTunes store
all-posts-feed: http://feeds.feedburner.com/JSR-all         #link to Feedburner all posts feed
twitter-link: https://twitter.com/#!/jsreligion
facebook-link: http://www.facebook.com/pages/Journal-of-Southern-Religion/197375710340300
email-subscribe-standalone: http://eepurl.com/llKWT

# Generation
source: ./_source
destination: ./public
plugins: ./_plugins
permalink: /:categories/:title.html

baseurl: http://jsreligion.org
