source: .
destination: ./_site
plugins: ./_plugins

exclude: _working/, Rakefile, _bootstrap/, _backups/

auto: false
server: false
server_port: 4000

#baseurl: http://lincolnmullen.com/jsrdev/
#baseurl: /
#url: http://jsr.fsu.edu
permalink: /:categories/:title.html

currentissue: vol13


